/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedCaptureRouteImport } from './routes/_authenticated/capture'
import { Route as AuthenticatedDossierPlusRouteImport } from './routes/_authenticated/dossier-plus'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'

const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_authenticated/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/_authenticated/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCaptureRoute = AuthenticatedCaptureRouteImport.update({
  id: '/_authenticated/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDossierPlusRoute =
  AuthenticatedDossierPlusRouteImport.update({
    id: '/_authenticated/dossier-plus',
    path: '/dossier-plus',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/_authenticated/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AuthenticatedAppRoute
  '/ask': typeof AuthenticatedAskRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/dossier-plus': typeof AuthenticatedDossierPlusRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesByTo {
  '/app': typeof AuthenticatedAppRoute
  '/ask': typeof AuthenticatedAskRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/dossier-plus': typeof AuthenticatedDossierPlusRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/capture': typeof AuthenticatedCaptureRoute
  '/_authenticated/dossier-plus': typeof AuthenticatedDossierPlusRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/app' | '/ask' | '/capture' | '/dossier-plus' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/app' | '/ask' | '/capture' | '/dossier-plus' | '/profile'
  id:
    | '__root__'
    | '/_authenticated/app'
    | '/_authenticated/ask'
    | '/_authenticated/capture'
    | '/_authenticated/dossier-plus'
    | '/_authenticated/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedCaptureRoute: typeof AuthenticatedCaptureRoute
  AuthenticatedDossierPlusRoute: typeof AuthenticatedDossierPlusRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/capture': {
      id: '/_authenticated/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dossier-plus': {
      id: '/_authenticated/dossier-plus'
      path: '/dossier-plus'
      fullPath: '/dossier-plus'
      preLoaderRoute: typeof AuthenticatedDossierPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedCaptureRoute: AuthenticatedCaptureRoute,
  AuthenticatedDossierPlusRoute: AuthenticatedDossierPlusRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
